name: CI

# Controls when the workflow will run
on:

  push:
    branches: [ "main" ]
    
  pull_request:
    branches: [ "main" ]
    
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Set up JDK 21 (or your project's Java version)
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'  # You can change this to another JDK distribution if needed
          java-version: '21'

      # Run Maven commands
      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Run tests with Maven
        run: mvn test
