name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      # Checkout the correct branch
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: master 

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Create local Maven repository structure and copy local dependencies
      - name: Copy local dependencies
        run: |
          
          mkdir -p ~/.m2/repository/gpsUtil/gpsUtil/1.0.0
          cp TourGuide/libs/gpsUtil.jar ~/.m2/repository/gpsUtil/gpsUtil/1.0.0/gpsUtil-1.0.0.jar
         
          mkdir -p ~/.m2/repository/tripPricer/tripPricer/1.0.0
          cp TourGuide/libs/TripPricer.jar ~/.m2/repository/tripPricer/tripPricer/1.0.0/tripPricer-1.0.0.jar
         
          mkdir -p ~/.m2/repository/rewardCentral/rewardCentral/1.0.0
          cp TourGuide/libs/RewardCentral.jar ~/.m2/repository/rewardCentral/rewardCentral/1.0.0/rewardCentral-1.0.0.jar

      # Build and package the application with Maven, including tests
      - name: Build and package with Maven
        working-directory: TourGuide
        run: mvn clean package -Dtest=!**/*PerformanceTest.java

      # Build Docker image
      - name: Build Docker image
        run: docker build -t my-app-image:latest

      # Push Docker image to registry
      - name: Push Docker image
        run: docker push my-app-image:latest

      # SAST Acommnalyse statique
      - name: Run SonarQube analysis
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
        env:
          SONAR_HOST_URL: 'https://sonarcloud.io'
